#!/bin/sh
time="$(date +%A)"
case "$BLOCK_BUTTON" in
	1) notify-send "$( ~/.config/i3blocks/i3script/class_schedule )";;
	3) notify-send "$( ~/.config/i3blocks/i3script/class_schedule_full )";;
esac
echo $time

