#!/bin/bash
cw=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_CLASS WM_NAME | awk -F '"' '{print $2}' )
[[ -n $(echo $cw | grep -i "google") ]] && echo $cw | sed 's/ - Google Chrome//g' 2> /dev/null
[[ -z $cw  ]] && echo "Nothing here !" 2> /dev/null
echo $cw
