#!/bin/sh

case $BLOCK_BUTTON in
	1) mpc toggle | filter;;
	4) mpc prev | filter;;
	5) mpc next | filter;;
esac
icon=⏹
if [[ `mpc status | wc -l` -le 1 ]];then
	echo "no music"
else
	state=`mpc status | grep '\[' | cut -d '[' -f2 | cut -d ']' -f1`
	case $state in
		playing) icon=ﱘ;;
		paused) icon=ﱙ;;
	esac
	song_name=`mpc status | head -n 1 | cut -d '/' -f2 | cut -d '.' -f1`
	echo "$song_name $icon"
fi
