#!/bin/sh
case $BLOCK_BUTTON in
	1) mpc toggle ;;
	3) setsid st -e ncmpcpp 2> /dev/null ;;
	4) mpc prev ;;
	5) mpc next ;;
esac
icon=⏹
if [[ `mpc status | wc -l` -le 1 ]];then
	#mpd 2> /dev/null;
	#mpc add CloudMusic > /dev/null;
	#mpc random on;
	echo "no music playing"$icon
else
	state=`mpc status | grep '\[' | cut -d '[' -f2 | cut -d ']' -f1`
	case $state in
		playing) icon=ﱘ;;
		paused) icon=ﱙ;;
	esac
	song_name=`mpc status | head -n 1 | cut -d '/' -f2 | cut -d '.' -f1`
	echo "$song_name $icon"
fi
