#!/bin/sh

case $BLOCK_BUTTON in
	1) mpc toggle | filter;;
	4) mpc prev | filter;;
	5) mpc next | filter;;
esac
[[ `mpc status | wc -l` == 1 ]] && echo "no music"
song_name=`mpc status | head -n 1 | cut -d '/' -f2 | cut -d '.' -f1`
echo $song_name


