#!/bin/bash
echo "TODO"
case "$BLOCK_BUTTON" in
	1) if [[ -f ~/Desktop/DailyTODO/"$(date '+%m_%d')" ]];then
			notify-send "$(cat ~/Desktop/DailyTODO/"$(date '+%m_%d')")" 
		else
			notify-send "NO LIST FOUND ! 
Please press right click to build one!"
		fi
		;;
	3) st -e ~/Desktop/DailyTODO/todo.sh 2> /dev/null ;;
esac
