# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.config/oh-my-zsh"

source ~/.profile
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# fzf
export FZF_DEFAULT_OPTS='--height 40% --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
#export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_COMPLETION_TRIGGER='\'
#export FZF_TMUX_HEIGHT='80%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
source ~/.config/zsh/key-bindings.zsh
source ~/.config/zsh/completion.zsh

#if [ -f ~/.sconfig/zsh/zshrc ]; then
	#source ~/.sconfig/zsh/zshrc
#fi

#Turn on Vi Mode
#bindkey -v
#function zle-keymap-select {
	#if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
		#echo -ne '\e[1 q'
	#elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then
		#echo -ne '\e[5 q'
  #fi
#}

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias c="clear"
alias nf="neofetch"
alias ra="ranger"
alias cs="cowsay"
#alias sf="screenfetch"
alias tzh="trans -b :zh"
alias stn="shutdown -h now"
alias mpvoo="mpv --loop"
alias mpvpl="mpv --playlist"
#alias ms="musicbox"
alias bl="python3 ~/Videos/BiliVideoDownloadforLinux.py"
alias lg="lazygit"
alias mo="sudo modprobe -r ideapad_laptop"
alias ni="nmcli dev wifi connect i-NUIST &"
alias nM="nmcli dev wifi connect MEIZU &"
alias nlt="nmcli dev wifi list"
# alias emacs="emacs -nw"
alias ltms="ssh root@47.99.77.16"
alias rb="reboot" 
alias sm="sudo NetworkManager"
alias vst="sudo systemctl start v2ray"
alias vr="sudo systemctl restart v2ray"
alias vsp="sudo systemctl stop v2ray"
#alias mdr="udisksctl mount -b /dev/sda1"
#alias umdr="udisksctl unmount -b /dev/sda1"
alias mntr="${HOME}/.config/zsh/mntr.sh"
alias doc="ranger ${HOME}/Documents"
alias dow="ranger ${HOME}/Downloads"
alias a="ranger ${HOME}/.config/awesome"
alias unzipc="unzip -O cp936"
alias cls="~/Desktop/cs.sh"
alias bgp="sxiv -ft ~/Pictures/BG_images/*.jpg ~/Pictures/BG_images/*.jpeg"
alias e="exit"
alias cg="cd ~/Github"
alias pc="proxychains"
alias a="ranger ${HOME}/.config/awesome"
alias n="nnn"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#cat ${HOME}/.cache/wal/sequences
